apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap-volume  
spec:
  containers:
    - name: conteiner-configmap-volume
      #image: k8s.gcr.io/busybox  
      image: gcr.io/google-samples/kubernetes-bootcamp:v1    
      command: ["/bin/sh", "-c", "ls /etc/config"]
      volumeMounts: 
      - name: volume-config # volume --> conteiner
        mountPath: /etc/config 
  
  volumes:
    - name: volume-config
      configMap:
          name: configmap-special-config # configMap(dados) --> volume
  
  #restartPolicy: Never
      
  