apiVersion: v1
kind: Pod
metadata:
  name: dapi-test-prod  
spec:
  containers:
    - name: test-container
      image: k8s.gcr.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_LEVEL_KEY
          valueFrom:
            configMapKeyRef:
              name: special-config # name of the ConfigMap created
              key: special.how        
  restartPolicy: Never  

